services:
  - type: web
    name: my-flask-chat
    repo: https://github.com/you/your-repo
    branch: main
    buildCommand: make install
    startCommand: make gunicorn
    envVars:
      - key: SECRET_KEY
        value: your-secret
      - key: DATABASE_URL
        fromDatabase:
          name: your-db
          property: CONNECTION_STRING
